### PR TITLE
add author reviews url to dict review output

### PR DESCRIPTION
**Pull request by hahnicity**
Fix a bug with parse_reviews_on_page where it would create duplicate reviews on the review list if we had already called the function. Also add a new dictionary entry for getting a url pointing to the list of the author's reviews.

### CODE REVIEW

**Comment by hahnicity** [comment]
Any thoughts? Otherwise I'm going to merge since all the tests are passing.

**Comment by adamlwgriffiths** [comment]
I think this affects an older commit, actually.
I'd change `parse_reviews_on_page` to just be a lazily accessed property:

```
# reviews.py

    def __init__(self, ...):
        ...
        self._all_reviews = None

    ...

    @property
     def reviews_on_page(self):
        if not self._reviews_on_page:
            for review_id in self.ids:
                try:
                    review = SubReview(self.soup, review_id, self.asin)
                    self._all_reviews.append(review)
                except ValueError:
                    pass
        return self._all_reviews
```

Just lazily load content, like with the soup property.
That way you're just accessing properties, rather than having to know to call certain functions before accessing them.
This is in reviews.py and also in reviewer.py.

Later on, we can even remove the 'self._property' values and just use a cache decorator.


URL arg for `class Reviewer` should be uppercase to be consistent with the rest of the API and bottlenose.

URL for reviewer should be None by default, with the addition of a ReviewerID arg.
This way you can pass in `Reviewer(ReviewerID="ABC123")`, as with the other classes.

We'll also need to a brief example to the README

Cheers!

**Comment by hahnicity** [comment]
I can change the `parse_reviews` function to save state and not regenerate. I had initially written it the way that it is right now because I figured if the html changed then the function would be able to reparse the reviews. But because the self.soup property is static the html won't change, so I can see my error. 

As per the UpperCamelCase question: I would prefer that python packages stick to pep8 coding standards in spite of the fact that it does not align with existing coding standards. Thoughts?

**Comment by adamlwgriffiths** [comment]
I prefer PEP-8 too, but because of the integration with Bottlenose, which just uses the Amazon Camel case values, it's better to be consistently bad, than in-consistently good.

**Comment by adamlwgriffiths** [comment]
There's no need to make it a requirement to call a function before you can access all_reviews.
Just make all_reviews an @property decorated method and do the logic there.

    def reviews_on_page(self):
        if not self._reviews_on_page:
            for review_id in self.ids:
                try:
                    review = SubReview(self.soup, review_id, self.asin)
                    self._reviews_on_page.append(review)
                except ValueError:
                    pass
        return self._reviews_on_page

**Comment by hahnicity** [comment]
I was thinking that eventually we could convert the whole thing to pep8 and leave the bottlenose silliness as is. But sure if you're more interested in being consistent until we hit that point then I can see their merit.

As to the last point I think I can understand it from, once again, a consistency POV. So I'll change it tonight.

**Comment by adamlwgriffiths** [comment]
Awesome!

**Pull request merged**
