### PR TITLE
Add review batch parsing.

### PR DESCRIPTION
**Pull request by hahnicity**
The problem with the previous method was that we would have to go to an entirely new url each time, load up the html and then parse through it. This is a really time consuming process. Its much easier to load up all of the reviews on one page and parse them all in one shot. 

I think that we should keep the old method because it's still valid and can fill a niche, but for bulk data collection this will be the way to go.

### CODE REVIEW

**Comment by hahnicity** [comment]
I'm going to merge this if there are no objections. I've run the tests and everything is passing now; I've also done a bit of testing with a tool that I'm writing right now and the batch processing is working well too.

**Comment by adamlwgriffiths** [comment]
something trivial in SubReview.
`rating` and `date` do the following logic

```
if not self.value:
  value = get_value()
  if value:
    self.value = process_data(value)
  else:
    self.value = value
```
I'm not sure of the purpose of the last line.
My only concern is that you may get an empty HTML node or some such (where `if value` equates to False), which later on gets passed out as a value.

Regarding the MaxQPS and `rate_limit` call.
Can we re-instate the `rate_limit` in the soup download functions, but just modify the rate_limit logic.
Either just immediately return, or make it check MaxQPS with `hasattr(api, 'MaxQPS')`.
That should (maybe) fix the MaxQPS not being present thing.
It also makes it easier to re-add once a version with MaxQPS support is released.


Otherwise, if tests are passing, and you're happy with the API, then go ahead and merge it in =)

**Comment by hahnicity** [comment]
In regards to MaxQPS in the soup download; I don't think that makes sense. We aren't actually going through the amazon API so there's no reason to rate limit our calls if we're just making GET requests.

By default we should be supporting the MaxQPS arg because requirements.txt points to master of the amazon-product-api-python-whatever pkg.

In regards to the date and ratings parsing, I'm not happy about duplicating some of the logic but I'm not sure if I can get around it cleanly. I can always implement a decorator or a context manager but I'm not convinced the value in implementation is worth it.

**Comment by adamlwgriffiths** [comment]
Prior to integrating with the Amazon API, I was able to scrape HTML incredibly fast and with many workers.
Once I integrated, I started getting a lot of error HTTP responses.
I could be wrong, but I believe that Amazon cross-checking IPs for API requests with normal HTTP requests and applying a rate limit to both.


MaxQPS probably won't be supported if this is pushed to PyPi.


I was just trying to imply that the
```
    else:
        self.value = value
```
isn't needed.

I'm not worried about code duplication. If it works, it works.
As long as the API is consistent and makes sense, then the internals can change however much we want without affecting any users.


Ah, another thing, can you put a quick example in the README of the new review parser?
Just a quick demo.

Cheers =)

**Comment by hahnicity** [comment]
Hmm.. I'd like to get some data on that cause that sounds like a neat little bit of engineering amazon would have to do in order to get that whole thing to work.

OK I'll fix the duplication and then add some README instructions

**Comment by adamlwgriffiths** [comment]
It's totally anecdotal and could be wrong =P

**Pull request merged**
